<a href="https://colab.research.google.com/github/TFremon/CHE-2064/blob/main/HW1_Antoine_Fitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://raw.githubusercontent.com/profteachkids/CHE2064_Spring2022/main/WaterVaporPressure.csv

--2022-01-29 20:04:55--  https://raw.githubusercontent.com/profteachkids/CHE2064_Spring2022/main/WaterVaporPressure.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1300 (1.3K) [text/plain]
Saving to: ‘WaterVaporPressure.csv.8’

WaterVaporPressure. 100%[===================>]   1.27K  --.-KB/s    in 0s      

2022-01-29 20:04:55 (29.9 MB/s) - ‘WaterVaporPressure.csv.8’ saved [1300/1300]



In [ ]:
import numpy as np
from scipy.optimize import minimize
from plotly.subplots import make_subplots
import plotly.io as pio
pio.templates.default=('plotly_dark')


In [ ]:
data = np.loadtxt('WaterVaporPressure.csv', delimiter=',')
data

array([[2.9315e+02, 2.4000e+03],
       [3.0315e+02, 4.2660e+03],
       [3.1315e+02, 7.3330e+03],
       [3.2315e+02, 1.2332e+04],
       [3.3315e+02, 1.9932e+04],
       [3.4315e+02, 3.1224e+04],
       [4.1275e+02, 3.5700e+05],
       [4.3285e+02, 6.1300e+05],
       [4.5125e+02, 9.6000e+05],
       [4.6315e+02, 1.2550e+06],
       [4.7335e+02, 1.5620e+06],
       [4.8255e+02, 1.8850e+06],
       [4.9265e+02, 2.2980e+06],
       [5.0415e+02, 2.8500e+06],
       [5.0777e+02, 3.0430e+06],
       [5.2128e+02, 3.8540e+06],
       [5.3518e+02, 4.8510e+06],
       [5.4149e+02, 5.3640e+06],
       [5.5260e+02, 6.3660e+06],
       [5.5797e+02, 6.8990e+06],
       [5.6169e+02, 7.2880e+06],
       [5.7131e+02, 8.3710e+06],
       [6.4595e+02, 2.1674e+07],
       [6.4604e+02, 2.1794e+07],
       [6.4607e+02, 2.1804e+07],
       [6.4709e+02, 2.1336e+07]])

In [ ]:
T = data[:, 0]
log10P = np.log10(data[:, 1])
T, log10P

(array([293.15, 303.15, 313.15, 323.15, 333.15, 343.15, 412.75, 432.85,
        451.25, 463.15, 473.35, 482.55, 492.65, 504.15, 507.77, 521.28,
        535.18, 541.49, 552.6 , 557.97, 561.69, 571.31, 645.95, 646.04,
        646.07, 647.09]),
 array([3.38021124, 3.63002085, 3.86528168, 4.09103352, 4.29955088,
        4.49448854, 5.55266822, 5.78746047, 5.98227123, 6.09864373,
        6.19368103, 6.27531135, 6.36135002, 6.45484486, 6.48330195,
        6.58591171, 6.68583127, 6.72948877, 6.80386663, 6.83878614,
        6.86260836, 6.92277734, 7.33593907, 7.33833695, 7.33853617,
        7.329113  ]))

In [ ]:
def sse(v):
  a,b,c=v

  return np.sum((a-b/(c+T)-log10P)**2)

In [ ]:
g = [1., 2., 3.]
a,b,c=minimize(sse, g).x
a,b,c

(10.208693007101473, 1756.357408949045, -36.02759306751273)

In [196]:
fig=make_subplots()
fig.add_scatter(x=T, y=log10P, mode='markers', name='Raw Data')
Tplot = np.linspace(273.15, 650, 1000)
fig.add_scatter(x=Tplot, y=a-b/(c+Tplot), mode='lines', name='Nonlinear regression' )

In [202]:
Q = np.c_[T, -log10P, np.ones_like(T)]
h = T*log10P
a2, c2, d2 =np.linalg.solve(Q.T @ Q, Q.T @ h)
b2 = a2*c2 - d2



In [205]:
fig2=make_subplots()
fig2.add_scatter(x=T, y=log10P, mode='markers', name='Raw Data')
Tplot = np.linspace(273.15, 650, 1000)
fig2.add_scatter(x=Tplot, y=a2-b2/(c2+Tplot), mode='lines', name='Linear regression' )
fig2.add_scatter(x=Tplot, y=a-b/(c+Tplot), mode='lines', name='Nonlinear regression' )